version: "3.8"
services:

  gatlin-express:
    build: ./
    container_name: gatlin-express
    volumes:
      - ./:/usr/src/app
      - gatlin-express_node_modules:/usr/src/app/node_modules


volumes:
  gatlin-express_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules